version: '3.8'

services:
  perpustakaan:
    build: .
    ports:
      - "9090:9090"
      - "9091:9091"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/perpustakaan
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - GRPC_SERVER_PORT=9090
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: perpustakaan
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
